---
kind: pipeline
type: exec
name: on-host
steps:
  - name: build
    when:
      branch:
        - main
    environment:
      CI_DEPLOY_PWD:
        from_secret: CI_DEPLOY_PWD
    commands:
      - cd $CI_DEPLOY_PWD
      - ./deploy.sh

---
kind: signature
hmac: 01ce46b68244c54fe31af44a915e36f593787e596f6298c741d5f3272aacbe66

...
