when:
  - event: push
    branch: main

labels:
  backend: local

steps:
  - name: deploy
    image: bash
    environment:
        CI_DEPLOY_PWD:
            from_secret: CI_DEPLOY_PWD
    commands:
      - cd $CI_DEPLOY_PWD
      - ./deploy.sh
